#This program says hello and asks for my name
print("Hello World!")
print('What is your name? ')
myName = input()
print("It's good time to meet you " + myName)
print("The leghts of your name is ")
print(len(myName))
print("what is your age? ")
myAge = input()
print("You will be " + str(int(myAge) + 1) + " in next year")